### ISSUE TITLE
GPX File validation fails if uploaded file contains comments before the gpx element

### ISSUE THREAD

**Issue by philipflohr** [alexboia/WP-Trip-Summary#87]
First of all, thank you for this great plugin!

I have an issue using some of my GPX files which I recorded. The files contain some comments before the gpx data.

The issue here is that GPX file validation fails if the gpx element is not in the string returned by fread `lib/validate/GpxDocument.php` on line 63.

```php
$buffer = @fread($testFilePointer, $this->_bufferLength);

if ($buffer) {
	if (function_exists('mb_stripos')) {
		$xmlPos = mb_stripos($buffer, '<?xml', 0, 'UTF-8');
		$gpxMarkerPos = mb_stripos($buffer, '<gpx', 0, 'UTF-8');
	} else {
		$xmlPos = stripos($buffer, '<?xml');
		$gpxMarkerPos = stripos($buffer, '<gpx');
	}
	
	$isValid = ($xmlPos >= 0 || $xmlPos <= 5)
		&& $gpxMarkerPos > 0;
}
```

This validation code has multiple issues, the one which is relevant for my use case is that if the gpx data is more than _bufferLength from the start of the file, the validation will fail.

An example input file could start like
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Created with BasicAirData GPS Logger for Android - ver. 3.1.4 -->
<!-- Track 6 = 28 TrackPoints + 0 Placemarks -->

<!-- Track Statistics (based on Total Time | Time in Movement): -->
<!--  Distance = 0 m -->
<!--  Duration = 00:27 | 00:00 -->
<!--  Altitude Gap = -4 m -->
<!--  Max Speed = 0 km/h -->
<!--  Avg Speed = 0,0 |  km/h -->
<!--  Activity = other -->

<gpx version....
```

**To Reproduce**
1. Add a GPX track to a post. The track needs to have some lines of xml comment before the gpx element

**Expected behavior**
The validation should not fail.

**Possible solutions**
There are several solutions to this.
For my use case it would be enough to just read more data if the gpx element is not yet found:
```php
if ($buffer) {
	if (function_exists('mb_stripos')) {
		$xmlPos = mb_stripos($buffer, '<?xml', 0, 'UTF-8');
	} else {
		$xmlPos = stripos($buffer, '<?xml');
	}
	if (! $xmlPos == 0) {
		@fclose($testFilePointer);
		return false;
	}
	do {
		$buffer = @fread( $testFilePointer, $this->_bufferLength );
		if ( ! $buffer ) {
			@fclose($testFilePointer);
			return false;
		}
		if ( function_exists( 'mb_stripos' ) ) {
			$gpxMarkerPos = mb_stripos( $buffer, '<gpx', 0, 'UTF-8' );
		} else {
			$gpxMarkerPos = stripos( $buffer, '<gpx' );
		}
	} while (!$gpxMarkerPos >0);
}

@fclose($testFilePointer);
return true;
```

still this code is far from perfect.

I'd suggest something like
```php
public function validate($filePath) {
        if (empty($filePath)) {
	        throw new InvalidArgumentException('File path may not be empty');
        }
        
        if (!is_readable($filePath)) {
	        return false;
        }
        
        
        $fileContent = file_get_contents($filePath);
        if (!$fileContent) {
	        return false;
        }
        if (function_exists('mb_stripos')) {
	        $xmlPos = mb_stripos($fileContent, '<?xml', 0, 'UTF-8');
	        $gpxMarkerPos = mb_stripos($fileContent, '<gpx', 0, 'UTF-8');
        }else {
	        $xmlPos = stripos($fileContent, '<?xml');
	        $gpxMarkerPos = stripos( $fileContent, '<gpx' );
        }
        return (is_int($xmlPos) && is_int($gpxMarkerPos)) && ($xmlPos < $gpxMarkerPos);
}
```

This still does not really validate the file but it should accept all valid GPX files.

**Comment by alexboia** [comment]
Hi Philip, 

First of all, thanks for the fix. Especially since I've rather busy this last year and have fallen short of what I wanted to do to maintain and move it forward. I've merged your code and will be updating the tests as well.

This piece of code, in particular, makes me feel like Indiana Jones in the catacombs of Venice - I don't think I've touched it ever since I wrote it. The sad part is I did not think of GPX file having comments at their very beginning. I do think this could fix some issue someone was complaining about, but for some reason, could not send me the file he was having issues with. 

By the way, you were saying something about multiple issues so my question would be what would those issues be and how would you rewrite it, (preferably short of performing XML parsing of the file itself, which I did not want to go into anyway)?

Again, thanks for your help,
Alex.

**Comment by philipflohr** [comment]
Hi,

thanks for merging my fix. The other issue is the rather obvious one, the function does not actually validate that the input data is a valid GPX file. So passing the upload check does not guarantee the uploaded file is actually usable by the plugin. There are gpx libraries like https://github.com/Sibyx/phpGPX - likely I would have used one to validate the input file.

**Comment by alexboia** [comment]
Actually that's by design - I didn't want to go into parsing a potentially large file just to validate (successful parsing of an XML file does not guarantee it is actually a valid GPX format so one must go further and do a schema validation as well). The topic, however, remains an open question, as far as I am concerned, so, If a stricter check would be required at some point, I would go with configurable strictness: just checking if it correctly loads as an XML file or do a schema validation as well.

On the other hand, this plugin has a built-in GPX parser and so (though parser only, not writer), which attempts to extract whatever is possible from that file (if correctly loaded), then does an ST_Simplify (Douglas-Peucker) on that data to obtain something that's more lightweight for browser rendering (essentially a track with less points), without affecting the original data. Hence my approach for looser validation.
